[package]
name = "wirepenguin"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = "0.35.0"
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = { version = "0.28.0", features = ["termion"] }
serde = "1.0.219"
tokio = { version = "1", features = ["full"] }
